#! /bin/sh -ex
cd "src/tup/version"
version=`git describe` ; (echo '#include "tup/version.h"'; echo "const char tup_version[] = \"$version\";") > version.c
gcc -c version.c -o version.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src 
cd "../tup"
gcc -c main.c -o main.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src 
cd "../server"
gcc -c fuse_server.c -o fuse_server.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src `pkg-config fuse --cflags`
gcc -c fuse_fs.c -o fuse_fs.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src `pkg-config fuse --cflags`
gcc -c master_fork.c -o master_fork.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src 
cd "../monitor"
gcc -c inotify.c -o inotify.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src 
cd "../flock"
gcc -c fcntl.c -o fcntl.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../../src 
cd "../../lua"
gcc -c lapi.c -o lapi.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lcode.c -o lcode.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lctype.c -o lctype.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ldebug.c -o ldebug.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ldo.c -o ldo.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ldump.c -o ldump.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lfunc.c -o lfunc.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lgc.c -o lgc.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c llex.c -o llex.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lmem.c -o lmem.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lobject.c -o lobject.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lopcodes.c -o lopcodes.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lparser.c -o lparser.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lstate.c -o lstate.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lstring.c -o lstring.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ltable.c -o ltable.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ltm.c -o ltm.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lundump.c -o lundump.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lvm.c -o lvm.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lzio.c -o lzio.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lauxlib.c -o lauxlib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lbaselib.c -o lbaselib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lbitlib.c -o lbitlib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lcorolib.c -o lcorolib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ldblib.c -o ldblib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c liolib.c -o liolib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lmathlib.c -o lmathlib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c loslib.c -o loslib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lstrlib.c -o lstrlib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c ltablib.c -o ltablib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c loadlib.c -o loadlib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c linit.c -o linit.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc -c lutf8lib.c -o lutf8lib.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
ar crs liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o lutf8lib.o
gcc -c lua.c -o lua.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DLUA_USE_POSIX 
gcc lua.o liblua.a -o lua -lm 
cd "../luabuiltin"
../lua/lua xxd.lua builtin.lua luabuiltin.h
cd "../tup"
gcc -c bin.c -o bin.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c colors.c -o colors.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c config.c -o config.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c create_name_file.c -o create_name_file.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c db.c -o db.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c debug.c -o debug.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c delete_name_file.c -o delete_name_file.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c dircache.c -o dircache.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c entry.c -o entry.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c environ.c -o environ.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c estring.c -o estring.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c file.c -o file.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c fslurp.c -o fslurp.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c graph.c -o graph.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c if_stmt.c -o if_stmt.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c init.c -o init.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c lock.c -o lock.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c luaparser.c -o luaparser.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c option.c -o option.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c parser.c -o parser.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c path.c -o path.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c pel_group.c -o pel_group.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c platform.c -o platform.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c privs.c -o privs.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c progress.c -o progress.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c send_event.c -o send_event.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c string_tree.c -o string_tree.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c thread_tree.c -o thread_tree.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c timespan.c -o timespan.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c tupid_tree.c -o tupid_tree.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c updater.c -o updater.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c vardb.c -o vardb.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c vardict.c -o vardict.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c variant.c -o variant.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c varsed.c -o varsed.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
cd "../sqlite3"
gcc -c sqlite3.c -o sqlite3.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -w -DSQLITE_TEMP_STORE=2 -DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION 
cd "../inih"
gcc -c ini.c -o ini.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src -Wno-cast-qual -DINI_ALLOW_MULTILINE=0 
cd "../compat"
gcc -c utimensat_linux.c -o utimensat_linux.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
gcc -c dummy.c -o dummy.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -D_FILE_OFFSET_BITS=64 -I../../src 
cd "../.."
ar crs libtup_client.a src/tup/vardict.o src/tup/send_event.o src/tup/flock/fcntl.o
cp src/tup/vardict.h tup_client.h
gcc src/tup/bin.o src/tup/colors.o src/tup/config.o src/tup/create_name_file.o src/tup/db.o src/tup/debug.o src/tup/delete_name_file.o src/tup/dircache.o src/tup/entry.o src/tup/environ.o src/tup/estring.o src/tup/file.o src/tup/fslurp.o src/tup/graph.o src/tup/if_stmt.o src/tup/init.o src/tup/lock.o src/tup/luaparser.o src/tup/option.o src/tup/parser.o src/tup/path.o src/tup/pel_group.o src/tup/platform.o src/tup/privs.o src/tup/progress.o src/tup/send_event.o src/tup/string_tree.o src/tup/thread_tree.o src/tup/timespan.o src/tup/tupid_tree.o src/tup/updater.o src/tup/vardb.o src/tup/vardict.o src/tup/variant.o src/tup/varsed.o src/tup/tup/main.o src/tup/monitor/inotify.o src/tup/flock/fcntl.o src/tup/server/fuse_fs.o src/tup/server/fuse_server.o src/tup/server/master_fork.o src/tup/version/version.o src/inih/ini.o src/compat/dummy.o src/compat/utimensat_linux.o src/sqlite3/sqlite3.o src/lua/liblua.a -o tup `pkg-config fuse --libs` -lm -lpthread 
